create table bank_clients (
       client_id NUMBER GENERATED by default on null as IDENTITY,
       first_name varchar2(50) not null,
       last_name varchar2(50) not null,
       contract_num varchar2(50) not null,
       client_location varchar2(100),
       telephone varchar2(15),
       money_summary number (11,2),
       UNIQUE (client_id)
);
